/** مكتبة الصور المرفقة مع التطبيق — تُستخدم كمصدر مؤقت إلى حين تفعيل الرفع عبر Supabase Storage. */
export const IMAGE_LIBRARY: readonly string[] = [
  "cafe-barista",
  "carbonara",
  "chicken-soup",
  "cold-brew",
  "creamy-soup",
  "croissant",
  "d-bread",
  "d-burger",
  "d-burger2",
  "d-cake",
  "d-cheesecake",
  "d-coffee-beans",
  "d-dessert",
  "d-espresso",
  "d-fish",
  "d-grill",
  "d-juice",
  "d-latte",
  "d-lemonade",
  "d-matcha",
  "d-mezze",
  "d-pancake",
  "d-pasta",
  "d-pasta2",
  "d-pastry",
  "d-pizza-margherita",
  "d-pizza-slice",
  "d-salad",
  "d-seafood-platter",
  "d-shawarma",
  "d-smoothie",
  "d-soup-veg",
  "d-soup2",
  "d-steak",
  "d-sushi-nigiri",
  "d-sushi-roll",
  "d-sushi-set",
  "damascus-cover",
  "damascus-logo",
  "discover-cover",
  "elixir-cover",
  "grain-bowl",
  "latte-art-cup",
  "latte-rosetta",
  "lentil-soup",
  "matcha-latte",
  "mocktail-mint",
  "p-cafe1",
  "p-cafe2",
  "p-cafe3",
  "p-coffee1",
  "p-coffee2",
  "p-coffee3",
  "p-coffee4",
  "p-rest1",
  "p-rest2",
  "p-rest3",
  "p-rest4",
  "p-rest5",
  "pizza-napoli",
  "r-andalus-cover",
  "r-andalus-logo",
  "r-burger-cover",
  "r-burger-logo",
  "r-damascus-alt",
  "r-green-cover",
  "r-green-logo",
  "r-hope-cover",
  "r-hope-logo",
  "r-noor-cover",
  "r-noor-logo",
  "r-pizza-cover",
  "r-pizza-logo",
  "r-seafood-cover",
  "r-seafood-logo",
  "r-sushi-cover",
  "r-sweets-cover",
  "r-sweets-logo",
  "r-trattoria-cover",
  "scallops-dish",
  "spanish-latte",
  "sushi-logo",
  "sushi-platter",
  "trattoria-logo",
];

export const imagePath = (name: string) => `/images/${name}.jpg`;

/** صور مقترحة حسب نوع المحتوى. */
export const SUGGESTED_DISH_IMAGES = IMAGE_LIBRARY.filter((name) => name.startsWith("d-"));
export const SUGGESTED_PLACE_IMAGES = IMAGE_LIBRARY.filter(
  (name) => name.startsWith("r-") || name.startsWith("p-"),
);
